# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dW7TMmE+LAl4K1/rzE3JJcJnuqaxM4n/3gNEqpo0nrcS73SVTX0U3EwbGIcKa++63uyKwrTEMX4NwSdF1JQTEOAEjqkPBy9OoedshYgFoINnWyl+TYycTFRlvbDkSab5TnmCI9QTv3OgU16YjBEQXbU8jPYrBL+tHpRnY0YXELiuYpF/CPmcFYzk48HYY8+S1l2PyKAUE43aIqInUVZAjelujx86tvz2jvIixGNPtIu/3xHBdUTsvZiwW8GGyLmU7OlRx6eSMWQYY8FyCbortHxCFSFIwOJVKAumd9u6PSfTl5kTHjbl/HhuUwz4m7u6E+sktvPT4mgu8dh3JQ6krqnG3RQ1iagZno+HTNTjx5NP/qVgwWhJ7R7sx0wAQlc2RyIMYSZBx5pQzcMM9uOqwAN5XyGrLuNLHEZph++OQBkH50qjZ7Y2E1tAwsYHFlL/YM79tRjZwSr8zXSEgmwlTFKmt5Tv0FUnyo5HFBLcsqMCOF9a6BMKq4KnqImV+2FXLeYIeVxdIFU2GqIn2A2UcMjNO4uStXgxrPEtcAUG447XnW+ISl5OS7EKVYtoPoGrmGKnloPhdxfHouwj2gwYvaoO9MWfMB5EImZ9Zz1WrlFJFX9xTghmmgGSWj7MsFg0CxILb+TU6l1W4R2ILN/D/8UG+kBbh2mSXQJQQ/FHRNg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
